allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects { subproject ->
    def configure = {
        if (subproject.hasProperty('android')) {
            subproject.android {
                if (namespace == null) {
                    namespace subproject.group
                }
                compileSdkVersion 35
            }
        }
    }
    if (subproject.state.executed) {
        configure()
    } else {
        subproject.afterEvaluate {
            configure()
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
